### ISSUE TITLE
Unable to differentiate Gerbs from the Big Dawg

### ISSUE THREAD

**Issue by keyneom** [danyim/gerbdawg#2]
Currently, when I attempt to access the site, I am unable to determine which attributes describe a gerb and which attributes more properly describe the big dawg.

(hint: firebase back-end doesn't seem to be responding with a nice list of attributes like I would have hoped. I am really hoping you still have some of them stored off somewhere and can add them to the source files as examples that can be added by anyone interested in cloning the repo)

**Comment by danyim** [comment]
I'm very sad to say that the `gerbsdawg` database is long lost. The app's Firebase account was tied to a work email from a previous (consulting) life.

If you could give me a scenario that you need identified, I can run it through the local copy that I have on my machine and tell you whether that's a "gerb" or the "Big Dawg" move.

**Comment by keyneom** [comment]
Unfortunately, I don't have a current scenario, it would have been for future reference :(
